export * from './numeral.js';
import numeral from './numeral.js';

import bpsFormatFactory from './formats/bps.js';
import bytesFormatFactory from './formats/bytes.js';
import currencyFormatFactory from './formats/currency.js';
import exponentialFormatFactory from './formats/exponential.js';
import ordinalFormatFactory from './formats/ordinal.js';
import percentageFormatFactory from './formats/percentage.js';
import timeFormatFactory from './formats/time.js';

import bgLocaleFactory from './locales/bg.js';
import csLocaleFactory from './locales/cs.js';
import daDkLocaleFactory from './locales/da-dk.js';
import deLocaleFactory from './locales/de.js';
import deChLocaleFactory from './locales/de-ch.js';
import enAuLocaleFactory from './locales/en-au.js';
import enGbLocaleFactory from './locales/en-gb.js';
import enZaLocaleFactory from './locales/en-za.js';
import esLocaleFactory from './locales/es.js';
import esEsLocaleFactory from './locales/es-es.js';
import etLocaleFactory from './locales/et.js';
import fiLocaleFactory from './locales/fi.js';
import frLocaleFactory from './locales/fr.js';
import frCaLocaleFactory from './locales/fr-ca.js';
import frChLocaleFactory from './locales/fr-ch.js';
import huLocaleFactory from './locales/hu.js';
import chsLocaleFactory from './locales/chs.js';
import itLocaleFactory from './locales/it.js';
import jaLocaleFactory from './locales/ja.js';
import lvLocaleFactory from './locales/lv.js';
import nlBeLocaleFactory from './locales/nl-be.js';
import nlNlLocaleFactory from './locales/nl-nl.js';
import noLocaleFactory from './locales/no.js';
import plLocaleFactory from './locales/pl.js';
import ptBrLocaleFactory from './locales/pt-br.js';
import ptPtLocaleFactory from './locales/pt-pt.js';
import ruLocaleFactory from './locales/ru.js';
import ruUaLocaleFactory from './locales/ru-ua.js';
import skLocaleFactory from './locales/sk.js';
import slLocaleFactory from './locales/sl.js';
import thLocaleFactory from './locales/th.js';
import trLocaleFactory from './locales/tr.js';
import ukUaLocaleFactory from './locales/uk-ua.js';
import viLocaleFactory from './locales/vi.js';


bpsFormatFactory(numeral);
bytesFormatFactory(numeral);
currencyFormatFactory(numeral);
exponentialFormatFactory(numeral);
ordinalFormatFactory(numeral);
percentageFormatFactory(numeral);
timeFormatFactory(numeral);

bgLocaleFactory(numeral);
csLocaleFactory(numeral);
daDkLocaleFactory(numeral);
deLocaleFactory(numeral);
deChLocaleFactory(numeral);
enAuLocaleFactory(numeral);
enGbLocaleFactory(numeral);
enZaLocaleFactory(numeral);
esLocaleFactory(numeral);
esEsLocaleFactory(numeral);
etLocaleFactory(numeral);
fiLocaleFactory(numeral);
frLocaleFactory(numeral);
frCaLocaleFactory(numeral);
frChLocaleFactory(numeral);
huLocaleFactory(numeral);
chsLocaleFactory(numeral);
itLocaleFactory(numeral);
jaLocaleFactory(numeral);
lvLocaleFactory(numeral);
nlBeLocaleFactory(numeral);
nlNlLocaleFactory(numeral);
noLocaleFactory(numeral);
plLocaleFactory(numeral);
ptBrLocaleFactory(numeral);
ptPtLocaleFactory(numeral);
ruLocaleFactory(numeral);
ruUaLocaleFactory(numeral);
skLocaleFactory(numeral);
slLocaleFactory(numeral);
thLocaleFactory(numeral);
trLocaleFactory(numeral);
ukUaLocaleFactory(numeral);
viLocaleFactory(numeral);
